server:
  port: 8881

#mybatis配置
mybatis:
  type-aliases-package: com.street.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  application:
    name: SpringCloud-Provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.185.226:3306/talent-ecosystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: JX210111
    password: 123456
